Repository paketo-buildpacks/php-dist, pull requests merged in 2022-04, with the labels that each got.

#366 `PHP_EXTENSION_DIR` is used by `paketo-buildpacks/composer-install`
  environment.go
Labels: semver:patch

#372 Adds PHP 8.1 to the dependencies list
  buildpack.toml
Labels: semver:minor

#370 Add filesystem SBOM capability
  build.go
  build_test.go
  buildpack.toml
  fakes/sbom_generator.go
  go.mod
  go.sum
  integration/simple_app_test.go
  run/main.go
Labels: semver:minor

#378 Bug Fix: user-provided config path should be .php.ini.d
  build.go
  build_test.go
  constants.go
  integration/testdata/app_loading_exts/.php.ini.d/some.ini
Labels: bug, semver:patch

#377 Remove buildpack.yml support
  README.md
  build.go
  build_test.go
  buildpack_yml_parser.go
  buildpack_yml_parser_test.go
  constants.go
  detect.go
  detect_test.go
  fakes/version_parser.go
  init_test.go
  integration/offline_test.go
  integration/reuse_layer_rebuild_test.go
  integration/simple_app_test.go
  integration/testdata/simple_app/buildpack.yml
  run/main.go
Labels: semver:major
